name: dino_wm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # 1. Core Environment
  - python=3.10
  - pip

  # 2. Key libraries best installed with Conda
  #    (Conda manages the complex non-Python parts well)
  - numpy
  - scipy
  - pillow
  - matplotlib
  - scikit-learn
  - h5py
  - opencv
  - ffmpeg
  - imageio
  - hydra-core
  - jupyterlab # Always good to have

  # 3. Major ML Frameworks (for GPU)
  - pytorch
  - torchvision
  - torchaudio
  - tensorflow
  - cudatoolkit=11.8 # Match this with your driver

  # 4. Pip for everything else
  - pip:
      - d4rl==1.1
      - dm-control
      - wandb
      - einops
      - decord
      - moviepy
      - robomimic
      - robosuite
      - gym
      - pybullet
