name: pusht
args: []
kwargs: 
  with_velocity: true
  with_target: true

dataset:
  _target_: "datasets.pusht_dset.load_pusht_slice_train_val"
  with_velocity: true
  n_rollout: null # 6000 (for online)
  val_rollout_steps: ${val_rollout_steps}
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/pusht_noise
  split_ratio: 0.9
  pretrain_ratio: 0
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}
  action_dim: 10

decoder_path: null
num_workers: 8